version: '3.8'

services:
  # Python Backend
  backend:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: wordexcel-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./python/uploads:/app/uploads
      - ./python/temp:/app/temp
    networks:
      - wordexcel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend
  frontend:
    build:
      context: ./python/frontend
      dockerfile: Dockerfile
    container_name: wordexcel-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - wordexcel-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: wordexcel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - wordexcel-network

networks:
  wordexcel-network:
    driver: bridge

volumes:
  uploads_data:
  temp_data:
